steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/kubernetes-390002/kubernetes/container2:${COMMIT_SHA}'
      - '.'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/kubernetes-390002/kubernetes/container2:${COMMIT_SHA}'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set','image','deployment/dhruv-container1-pod','dhruv-container2-pod=us-central1-docker.pkg.dev/kubernetes-390002/kubernetes/container2:${COMMIT_SHA}','--namespace','dhruv-namespace']  
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster1'
  
images:
  - 'us-central1-docker.pkg.dev/kubernetes-390002/kubernetes/container2:${COMMIT_SHA}'
